name: Build

on:
  push:
  workflow_dispatch:

env:
  PACT_BROKER_BASE_URL: https://viscountdefenestrateltd.pactflow.io 
  PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN }}
  REACT_APP_API_BASE_URL: http://localhost:8080
  TRAVIS_COMMIT: ${{ github.sha }}
  TRAVIS_BRANCH: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.1.x']
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2-beta
  #       with:
  #         node-version: '12'
  #     - name: Install
  #       run: npm i
  #     - name: Test
  #       run: make test
  #     - name: Publish pacts
  #       run: TRAVIS_BRANCH=${TRAVIS_BRANCH:11} make publish_pacts

  # Runs on branches as well, so we know the status of our PRs
  # can-i-deploy:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: docker pull pactfoundation/pact-cli:latest
  #     - name: Can I deploy?
  #       run: TRAVIS_BRANCH=${TRAVIS_BRANCH:11} make can_i_deploy

  # Only deploy from master
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: can-i-deploy
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: docker pull pactfoundation/pact-cli:latest
  #     - name: Deploy
  #       run: TRAVIS_BRANCH=${TRAVIS_BRANCH:11} make deploy
  #       if: github.ref == 'refs/heads/master'
